version: '3.8'

services:
  prod:
    build: "."
    ports:
        - "127.0.0.1:8000:8000"
    networks:
      - tests

  dev:
    build: "."
    volumes:
     - "./src:/wd/src"
    command: ["python", "app.py"]
    ports:
        - "127.0.0.1:8000:8000"
    networks:
      - tests

  tests:
    build: "./tests"
    volumes:
     - "./tests:/wd"
     - "./src:/wd/src"
    networks:
      - tests

networks:
  tests:
