version: '3.8'

services:
  prod:
    build: "."
    ports:
        - "127.0.0.1:8000:8000"

  dev:
    build: "."
    volumes:
     - "./:/wd"
    command: ["python", "app.py"]
    ports:
        - "127.0.0.1:8000:8000"
